previews:
  generation: off

services:
  - type: web
    name: simple-chat-nazariodicataldo
    runtime: docker
    plan: free
    region: frankfurt
    branch: master
    autoDeployTrigger: off
    dockerfilePath: ./docker/production/Dockerfile
    dockerContext: .
    healthCheckPath: /up
    renderSubdomainPolicy: enabled
    envVars:
      - key: APP_NAME
        value: Simple Chat
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: APP_URL
        fromService:
          name: simple-chat-nazariodicataldo
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: FRONTEND_URL
        fromService:
          name: simple-chat-nazariodicataldo
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          name: simple-chat-nazariodicataldo
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: SANCTUM_STATEFUL_DOMAINS
        fromService:
          name: simple-chat-nazariodicataldo
          type: web
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: REVERB_ALLOWED_ORIGINS
        fromService:
          name: simple-chat-nazariodicataldo
          type: web
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: DB_CONNECTION
        value: pgsql
      - key: CACHE_STORE
        value: database
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: SESSION_HTTP_ONLY
        value: "true"
      - key: SESSION_SAME_SITE
        value: lax
      - key: QUEUE_FAILED_DRIVER
        value: database-uuids
      - key: QUEUE_CONNECTION
        value: redis
      - key: REDIS_CLIENT
        value: phpredis
      - key: REDIS_DB
        value: "0"
      - key: REDIS_QUEUE_CONNECTION
        value: default
      - key: REDIS_QUEUE
        value: default
      - key: REDIS_QUEUE_RETRY_AFTER
        value: "90"
      - key: REDIS_QUEUE_BLOCK_FOR
        value: "5"
      - key: BROADCAST_CONNECTION
        value: reverb
      - key: REVERB_APP_ID
        value: simple-chat-production
      - key: REVERB_APP_KEY
        value: simple-chat-production-key
      - key: NEXT_PUBLIC_REVERB_APP_KEY
        value: simple-chat-production-key
      - key: REVERB_APP_SECRET
        generateValue: true
      - key: APP_KEY
        sync: false
      - key: DB_URL
        sync: false
      - key: REDIS_URL
        sync: false
